services:
  backend:
    build: ./backend
    ports:
      - "3001:3001"
    container_name: task2_insy7314-backend

  employee-portal:
    build: ./employee-portal
    ports:
      - "5173:5173"
    container_name: employee-portal

  frontend:
    build: ./frontend
    ports:
      - "5174:5174"
    container_name: frontend-portal
