services:
  backend:
    build: ./backend
    ports:
      - "3001:3001"
    container_name: task2_insy7314-backend
    environment:
      - MONGO_URI=mongodb://mongo:27017/paymentdb
    depends_on:
      - mongo

  employee-portal:
    build: ./employee-portal
    ports:
      - "5174:5174"
    container_name: employee-portal

  frontend:
    build: ./frontend
    ports:
     - "5173:5173"
    container_name: frontend-portal

  mongo:
    image: mongo:6.0
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
